import { CSharpTargetLanguage } from "quicktype-core";
import { StringOption, EnumOption } from "quicktype-core/dist/RendererOptions.js";
  
import { cSharpOptions as _cSharpOptions } from "quicktype-core/dist/language/CSharp.js";
import { all } from "quicktype-core/dist/language/All.js";
all.splice(all.findIndex(v => v.displayName === "C#"), 1)
all.unshift(new CSharpTargetLanguage("C#", ["csharp"], "cs"));
_cSharpOptions.namespace = new StringOption(
  "Namespace",
  null,
  null,
  "AutoGenerated"
);
_cSharpOptions.useList = new EnumOption(
  "array-type",
  "Use T[] or List<T>",
  [
    ["array", true],
    ["list", false],
  ]
);
